/**
 * Deliberately NOT `server-only`. This module holds no secrets — three labels,
 * three landing paths, three seeded email addresses that exist only to be
 * looked up. It is imported by the seed script, which runs outside Next
 * entirely, and by the marketing page that renders the buttons. Marking it
 * server-only breaks the first and buys nothing on the second.
 */

/**
 * The three demo identities, per spec §9.
 *
 * Deliberately keyed by a short slug rather than by email, so the URL that
 * mints a session cannot be used to probe for arbitrary accounts: only these
 * three strings resolve to anything. `app/api/demo/[persona]` rejects
 * everything else with a 404.
 *
 * Emails are resolved against the seeded users at request time rather than
 * hard-coding ids, because ids are regenerated by every nightly reset.
 */
export const DEMO_PERSONAS = {
  manager: {
    email: "dana.whitfield@porticoliving.example",
    label: "Property manager",
    landing: "/app",
  },
  resident: {
    email: "marcus.ellery@example.com",
    label: "Resident",
    landing: "/portal",
  },
  "resident-2": {
    email: "priya.raghavan@example.com",
    label: "Second resident",
    landing: "/portal",
  },
} as const;

export type DemoPersonaKey = keyof typeof DEMO_PERSONAS;

export function isDemoPersona(value: string): value is DemoPersonaKey {
  return Object.prototype.hasOwnProperty.call(DEMO_PERSONAS, value);
}
